FROM python:3.11.7-slim

WORKDIR /code
RUN pip install --upgrade pip && pip install poetry

# Avoid existing bug where poetry installs dependencies into a wrong directory:
RUN poetry config virtualenvs.create false

COPY poetry.lock pyproject.toml ./
RUN poetry lock
RUN poetry install --no-root --with=dev
COPY ./heraldecho ./heraldecho
COPY ./tests ./tests
COPY ./config.json ./

ENTRYPOINT ["python", "-m", "pytest", "tests/", "-v"]
