[tool.poetry]
name = "heraldecho"
version = "0.1.0"
description = "Configure periodic announcements in a multitude of ways"
authors = ["Creohex <paradise.source@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
jsonschema = "^4.21.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-mock = "^3.11.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
